#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProyectoHeladeria")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_USUARIO(TBL_USUARIO instance);
    partial void UpdateTBL_USUARIO(TBL_USUARIO instance);
    partial void DeleteTBL_USUARIO(TBL_USUARIO instance);
    partial void InsertTBL_CLIENTES(TBL_CLIENTES instance);
    partial void UpdateTBL_CLIENTES(TBL_CLIENTES instance);
    partial void DeleteTBL_CLIENTES(TBL_CLIENTES instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.ProyectoHeladeriaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this.GetTable<TBL_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CLIENTES> TBL_CLIENTES
		{
			get
			{
				return this.GetTable<TBL_CLIENTES>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USUARIO")]
	public partial class TBL_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USUARIO;
		
		private string _USU_USUARIO;
		
		private string _USU_CLAVE;
		
		private string _USU_TIPO_USUARIO;
		
		private System.Nullable<char> _USU_ESTADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnUSU_USUARIOChanging(string value);
    partial void OnUSU_USUARIOChanged();
    partial void OnUSU_CLAVEChanging(string value);
    partial void OnUSU_CLAVEChanged();
    partial void OnUSU_TIPO_USUARIOChanging(string value);
    partial void OnUSU_TIPO_USUARIOChanged();
    partial void OnUSU_ESTADOChanging(System.Nullable<char> value);
    partial void OnUSU_ESTADOChanged();
    #endregion
		
		public TBL_USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_USUARIO", DbType="VarChar(100)")]
		public string USU_USUARIO
		{
			get
			{
				return this._USU_USUARIO;
			}
			set
			{
				if ((this._USU_USUARIO != value))
				{
					this.OnUSU_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._USU_USUARIO = value;
					this.SendPropertyChanged("USU_USUARIO");
					this.OnUSU_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_CLAVE", DbType="VarChar(100)")]
		public string USU_CLAVE
		{
			get
			{
				return this._USU_CLAVE;
			}
			set
			{
				if ((this._USU_CLAVE != value))
				{
					this.OnUSU_CLAVEChanging(value);
					this.SendPropertyChanging();
					this._USU_CLAVE = value;
					this.SendPropertyChanged("USU_CLAVE");
					this.OnUSU_CLAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_TIPO_USUARIO", DbType="VarChar(100)")]
		public string USU_TIPO_USUARIO
		{
			get
			{
				return this._USU_TIPO_USUARIO;
			}
			set
			{
				if ((this._USU_TIPO_USUARIO != value))
				{
					this.OnUSU_TIPO_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._USU_TIPO_USUARIO = value;
					this.SendPropertyChanged("USU_TIPO_USUARIO");
					this.OnUSU_TIPO_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> USU_ESTADO
		{
			get
			{
				return this._USU_ESTADO;
			}
			set
			{
				if ((this._USU_ESTADO != value))
				{
					this.OnUSU_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._USU_ESTADO = value;
					this.SendPropertyChanged("USU_ESTADO");
					this.OnUSU_ESTADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CLIENTES")]
	public partial class TBL_CLIENTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CLIENTE;
		
		private string _CLI_NOMBRECOMPLETO;
		
		private string _CLI_CI;
		
		private string _CLI_NUMERO;
		
		private string _CLI_DIRECCION;
		
		private System.Nullable<char> _CLI_ESTADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLIENTEChanging(int value);
    partial void OnID_CLIENTEChanged();
    partial void OnCLI_NOMBRECOMPLETOChanging(string value);
    partial void OnCLI_NOMBRECOMPLETOChanged();
    partial void OnCLI_CIChanging(string value);
    partial void OnCLI_CIChanged();
    partial void OnCLI_NUMEROChanging(string value);
    partial void OnCLI_NUMEROChanged();
    partial void OnCLI_DIRECCIONChanging(string value);
    partial void OnCLI_DIRECCIONChanged();
    partial void OnCLI_ESTADOChanging(System.Nullable<char> value);
    partial void OnCLI_ESTADOChanged();
    #endregion
		
		public TBL_CLIENTES()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_NOMBRECOMPLETO", DbType="VarChar(100)")]
		public string CLI_NOMBRECOMPLETO
		{
			get
			{
				return this._CLI_NOMBRECOMPLETO;
			}
			set
			{
				if ((this._CLI_NOMBRECOMPLETO != value))
				{
					this.OnCLI_NOMBRECOMPLETOChanging(value);
					this.SendPropertyChanging();
					this._CLI_NOMBRECOMPLETO = value;
					this.SendPropertyChanged("CLI_NOMBRECOMPLETO");
					this.OnCLI_NOMBRECOMPLETOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_CI", DbType="VarChar(10)")]
		public string CLI_CI
		{
			get
			{
				return this._CLI_CI;
			}
			set
			{
				if ((this._CLI_CI != value))
				{
					this.OnCLI_CIChanging(value);
					this.SendPropertyChanging();
					this._CLI_CI = value;
					this.SendPropertyChanged("CLI_CI");
					this.OnCLI_CIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_NUMERO", DbType="VarChar(10)")]
		public string CLI_NUMERO
		{
			get
			{
				return this._CLI_NUMERO;
			}
			set
			{
				if ((this._CLI_NUMERO != value))
				{
					this.OnCLI_NUMEROChanging(value);
					this.SendPropertyChanging();
					this._CLI_NUMERO = value;
					this.SendPropertyChanged("CLI_NUMERO");
					this.OnCLI_NUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_DIRECCION", DbType="VarChar(100)")]
		public string CLI_DIRECCION
		{
			get
			{
				return this._CLI_DIRECCION;
			}
			set
			{
				if ((this._CLI_DIRECCION != value))
				{
					this.OnCLI_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._CLI_DIRECCION = value;
					this.SendPropertyChanged("CLI_DIRECCION");
					this.OnCLI_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> CLI_ESTADO
		{
			get
			{
				return this._CLI_ESTADO;
			}
			set
			{
				if ((this._CLI_ESTADO != value))
				{
					this.OnCLI_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._CLI_ESTADO = value;
					this.SendPropertyChanged("CLI_ESTADO");
					this.OnCLI_ESTADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
